"""added user-based llm table

Revision ID: 4b5dd3010a91
Revises: e209dc5a8156
Create Date: 2024-06-21 17:26:48.800460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import danswer
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = "4b5dd3010a91"
down_revision = "e209dc5a8156"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_llm_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column(
            "api_key", danswer.db.models.EncryptedString(), nullable=True
        ),
        sa.Column("api_base", sa.String(), nullable=True),
        sa.Column("api_version", sa.String(), nullable=True),
        sa.Column(
            "custom_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("default_model_name", sa.String(), nullable=False),
        sa.Column("fast_default_model_name", sa.String(), nullable=True),
        sa.Column("model_names", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("is_default_provider", sa.Boolean(), nullable=True),
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_llm_settings")
    # ### end Alembic commands ###
